on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - "mkdocs.yml"
      - "docs/**"
    branches:
      - master
  pull_request:
    paths-ignore:
      - "*.md"
      - "mkdocs.yml"
      - "docs/**"
  release:
    types:
      - published

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-20.04, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm install
  archive-vsix:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.x
      - run: npm install
      - name: Build VSIX package
        run: |
          npm install @vscode/vsce -g
          npm run build
          vsce package -o rde-ros-1-dev.vsix
      - uses: actions/upload-artifact@v4
        if: github.event_name == 'push'
        with:
          name: rde-ros-1-dev-vsix
          path: rde-ros-1-dev.vsix
